# generator comprehensions
# we use this for memory efficiency because
#  it will not store the entire list in memory 
# but it will generate the values on the fly.

numbers = ['1', '2', '3','2','3','2','3','2','3','2','1','2','3']
# sytax sum(expression for item in iterable if condition)
# for generator comprehension we use () instead of []
# use sum() function to get the sum of the values generated by the generator comprehension

number_gen = sum(int(x) for x in numbers if x > '3')
print(number_gen)